<?xml version="1.0" encoding="UTF-8"?><testrun name="MemberDAOImplTest (2)" project="WebStudy05_SpringMVC" tests="5" started="5" failures="0" errors="2" ignored="0">
  <testsuite name="kr.or.ddit.member.dao.MemberDAOImplTest" time="0.472">
    <testcase name="testSelectMemberList" classname="kr.or.ddit.member.dao.MemberDAOImplTest" time="0.001">
      <error>org.mybatis.spring.MyBatisSystemException: nested exception is org.apache.ibatis.builder.BuilderException: Error evaluating expression '@org.apache.commons.lang3.StringUtils@isNotBlank(simpleCondition.searchWord)'. Cause: org.apache.ibatis.ognl.OgnlException: source is null for getProperty(null, "searchWord")&#13;
	at org.mybatis.spring.MyBatisExceptionTranslator.translateExceptionIfPossible(MyBatisExceptionTranslator.java:96)&#13;
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:441)&#13;
	at com.sun.proxy.$Proxy41.selectList(Unknown Source)&#13;
	at org.mybatis.spring.SqlSessionTemplate.selectList(SqlSessionTemplate.java:224)&#13;
	at org.apache.ibatis.binding.MapperMethod.executeForMany(MapperMethod.java:147)&#13;
	at org.apache.ibatis.binding.MapperMethod.execute(MapperMethod.java:80)&#13;
	at org.apache.ibatis.binding.MapperProxy$PlainMethodInvoker.invoke(MapperProxy.java:145)&#13;
	at org.apache.ibatis.binding.MapperProxy.invoke(MapperProxy.java:86)&#13;
	at com.sun.proxy.$Proxy45.selectMemberList(Unknown Source)&#13;
	at kr.or.ddit.member.dao.MemberDAOImplTest.testSelectMemberList(MemberDAOImplTest.java:60)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)&#13;
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)&#13;
	at java.lang.reflect.Method.invoke(Method.java:498)&#13;
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)&#13;
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)&#13;
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)&#13;
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)&#13;
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)&#13;
	at org.springframework.test.context.junit4.statements.RunBeforeTestMethodCallbacks.evaluate(RunBeforeTestMethodCallbacks.java:75)&#13;
	at org.springframework.test.context.junit4.statements.RunAfterTestMethodCallbacks.evaluate(RunAfterTestMethodCallbacks.java:86)&#13;
	at org.springframework.test.context.junit4.statements.SpringRepeat.evaluate(SpringRepeat.java:84)&#13;
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)&#13;
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:252)&#13;
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:94)&#13;
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)&#13;
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)&#13;
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)&#13;
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)&#13;
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)&#13;
	at org.springframework.test.context.junit4.statements.RunBeforeTestClassCallbacks.evaluate(RunBeforeTestClassCallbacks.java:61)&#13;
	at org.springframework.test.context.junit4.statements.RunAfterTestClassCallbacks.evaluate(RunAfterTestClassCallbacks.java:70)&#13;
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)&#13;
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)&#13;
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:191)&#13;
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)&#13;
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:538)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:760)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:460)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:206)&#13;
Caused by: org.apache.ibatis.builder.BuilderException: Error evaluating expression '@org.apache.commons.lang3.StringUtils@isNotBlank(simpleCondition.searchWord)'. Cause: org.apache.ibatis.ognl.OgnlException: source is null for getProperty(null, "searchWord")&#13;
	at org.apache.ibatis.scripting.xmltags.OgnlCache.getValue(OgnlCache.java:48)&#13;
	at org.apache.ibatis.scripting.xmltags.ExpressionEvaluator.evaluateBoolean(ExpressionEvaluator.java:32)&#13;
	at org.apache.ibatis.scripting.xmltags.IfSqlNode.apply(IfSqlNode.java:34)&#13;
	at org.apache.ibatis.scripting.xmltags.MixedSqlNode.lambda$apply$0(MixedSqlNode.java:32)&#13;
	at java.util.ArrayList.forEach(ArrayList.java:1249)&#13;
	at org.apache.ibatis.scripting.xmltags.MixedSqlNode.apply(MixedSqlNode.java:32)&#13;
	at org.apache.ibatis.scripting.xmltags.TrimSqlNode.apply(TrimSqlNode.java:55)&#13;
	at org.apache.ibatis.scripting.xmltags.MixedSqlNode.lambda$apply$0(MixedSqlNode.java:32)&#13;
	at java.util.ArrayList.forEach(ArrayList.java:1249)&#13;
	at org.apache.ibatis.scripting.xmltags.MixedSqlNode.apply(MixedSqlNode.java:32)&#13;
	at org.apache.ibatis.scripting.xmltags.DynamicSqlSource.getBoundSql(DynamicSqlSource.java:39)&#13;
	at org.apache.ibatis.mapping.MappedStatement.getBoundSql(MappedStatement.java:305)&#13;
	at org.apache.ibatis.executor.CachingExecutor.query(CachingExecutor.java:87)&#13;
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:151)&#13;
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:145)&#13;
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:140)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)&#13;
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)&#13;
	at java.lang.reflect.Method.invoke(Method.java:498)&#13;
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:427)&#13;
	... 39 more&#13;
Caused by: org.apache.ibatis.ognl.OgnlException: source is null for getProperty(null, "searchWord")&#13;
&#13;
</error>
    </testcase>
    <testcase name="testSelectMember" classname="kr.or.ddit.member.dao.MemberDAOImplTest" time="0.428"/>
    <testcase name="testUpdateMember" classname="kr.or.ddit.member.dao.MemberDAOImplTest" time="0.006"/>
    <testcase name="testDeleteMember" classname="kr.or.ddit.member.dao.MemberDAOImplTest" time="0.003"/>
    <testcase name="testInsertMember" classname="kr.or.ddit.member.dao.MemberDAOImplTest" time="0.034">
      <error>java.lang.Exception: Unexpected exception, expected&lt;org.apache.ibatis.exceptions.PersistenceException&gt; but was&lt;org.springframework.dao.DataIntegrityViolationException&gt;&#13;
	at org.junit.internal.runners.statements.ExpectException.evaluate(ExpectException.java:30)&#13;
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)&#13;
	at org.springframework.test.context.junit4.statements.RunBeforeTestMethodCallbacks.evaluate(RunBeforeTestMethodCallbacks.java:75)&#13;
	at org.springframework.test.context.junit4.statements.RunAfterTestMethodCallbacks.evaluate(RunAfterTestMethodCallbacks.java:86)&#13;
	at org.springframework.test.context.junit4.statements.SpringRepeat.evaluate(SpringRepeat.java:84)&#13;
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)&#13;
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:252)&#13;
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:94)&#13;
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)&#13;
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)&#13;
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)&#13;
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)&#13;
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)&#13;
	at org.springframework.test.context.junit4.statements.RunBeforeTestClassCallbacks.evaluate(RunBeforeTestClassCallbacks.java:61)&#13;
	at org.springframework.test.context.junit4.statements.RunAfterTestClassCallbacks.evaluate(RunAfterTestClassCallbacks.java:70)&#13;
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)&#13;
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)&#13;
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:191)&#13;
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)&#13;
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:538)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:760)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:460)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:206)&#13;
Caused by: org.springframework.dao.DataIntegrityViolationException: &#13;
### Error updating database.  Cause: java.sql.SQLIntegrityConstraintViolationException: ORA-01400: cannot insert NULL into ("DDIT"."MEMBER"."MEM_REGNO1")
&#13;
### The error may exist in file [D:\A_TeachingMaterial\6.JspSpring\workspace\WebStudy05_SpringMVC\target\classes\kr\or\ddit\mybatis\mappers\Member.xml]&#13;
### The error may involve kr.or.ddit.member.dao.MemberDAO.insertMember-Inline&#13;
### The error occurred while setting parameters&#13;
### SQL: INSERT INTO MEMBER (                 MEM_ID                      , MEM_PASS                   , MEM_NAME                   , MEM_REGNO1                 , MEM_REGNO2                 , MEM_BIR                    , MEM_ZIP                    , MEM_ADD1                   , MEM_ADD2                   , MEM_HOMETEL                , MEM_COMTEL                 , MEM_HP                     , MEM_MAIL                   , MEM_JOB                    , MEM_LIKE                   , MEM_MEMORIAL               , MEM_MEMORIALDAY           , MEM_IMG     ) VALUES (                     ?      , ?      , ?      , ?      , ?      , ?      , ?      , ?      , ?      , ?      , ?      , ?      , ?      , ?      , ?      , ?      , ?      , ?    )&#13;
### Cause: java.sql.SQLIntegrityConstraintViolationException: ORA-01400: cannot insert NULL into ("DDIT"."MEMBER"."MEM_REGNO1")

; SQL []; ORA-01400: cannot insert NULL into ("DDIT"."MEMBER"."MEM_REGNO1")
; nested exception is java.sql.SQLIntegrityConstraintViolationException: ORA-01400: cannot insert NULL into ("DDIT"."MEMBER"."MEM_REGNO1")
&#13;
	at org.springframework.jdbc.support.SQLErrorCodeSQLExceptionTranslator.doTranslate(SQLErrorCodeSQLExceptionTranslator.java:242)&#13;
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:73)&#13;
	at org.mybatis.spring.MyBatisExceptionTranslator.translateExceptionIfPossible(MyBatisExceptionTranslator.java:91)&#13;
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:441)&#13;
	at com.sun.proxy.$Proxy41.insert(Unknown Source)&#13;
	at org.mybatis.spring.SqlSessionTemplate.insert(SqlSessionTemplate.java:272)&#13;
	at org.apache.ibatis.binding.MapperMethod.execute(MapperMethod.java:62)&#13;
	at org.apache.ibatis.binding.MapperProxy$PlainMethodInvoker.invoke(MapperProxy.java:145)&#13;
	at org.apache.ibatis.binding.MapperProxy.invoke(MapperProxy.java:86)&#13;
	at com.sun.proxy.$Proxy45.insertMember(Unknown Source)&#13;
	at kr.or.ddit.member.dao.MemberDAOImplTest.testInsertMember(MemberDAOImplTest.java:44)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)&#13;
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)&#13;
	at java.lang.reflect.Method.invoke(Method.java:498)&#13;
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)&#13;
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)&#13;
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)&#13;
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)&#13;
	at org.junit.internal.runners.statements.ExpectException.evaluate(ExpectException.java:19)&#13;
	... 23 more&#13;
Caused by: java.sql.SQLIntegrityConstraintViolationException: ORA-01400: cannot insert NULL into ("DDIT"."MEMBER"."MEM_REGNO1")
&#13;
	at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:494)&#13;
	at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:446)&#13;
	at oracle.jdbc.driver.T4C8Oall.processError(T4C8Oall.java:1054)&#13;
	at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:623)&#13;
	at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:252)&#13;
	at oracle.jdbc.driver.T4C8Oall.doOALL(T4C8Oall.java:612)&#13;
	at oracle.jdbc.driver.T4CPreparedStatement.doOall8(T4CPreparedStatement.java:226)&#13;
	at oracle.jdbc.driver.T4CPreparedStatement.doOall8(T4CPreparedStatement.java:59)&#13;
	at oracle.jdbc.driver.T4CPreparedStatement.executeForRows(T4CPreparedStatement.java:910)&#13;
	at oracle.jdbc.driver.OracleStatement.doExecuteWithTimeout(OracleStatement.java:1119)&#13;
	at oracle.jdbc.driver.OraclePreparedStatement.executeInternal(OraclePreparedStatement.java:3780)&#13;
	at oracle.jdbc.driver.T4CPreparedStatement.executeInternal(T4CPreparedStatement.java:1343)&#13;
	at oracle.jdbc.driver.OraclePreparedStatement.execute(OraclePreparedStatement.java:3887)&#13;
	at oracle.jdbc.driver.OraclePreparedStatementWrapper.execute(OraclePreparedStatementWrapper.java:1079)&#13;
	at net.sf.log4jdbc.PreparedStatementSpy.execute(PreparedStatementSpy.java:418)&#13;
	at org.apache.commons.dbcp2.DelegatingPreparedStatement.execute(DelegatingPreparedStatement.java:94)&#13;
	at org.apache.commons.dbcp2.DelegatingPreparedStatement.execute(DelegatingPreparedStatement.java:94)&#13;
	at org.apache.ibatis.executor.statement.PreparedStatementHandler.update(PreparedStatementHandler.java:47)&#13;
	at org.apache.ibatis.executor.statement.RoutingStatementHandler.update(RoutingStatementHandler.java:74)&#13;
	at org.apache.ibatis.executor.SimpleExecutor.doUpdate(SimpleExecutor.java:50)&#13;
	at org.apache.ibatis.executor.BaseExecutor.update(BaseExecutor.java:117)&#13;
	at org.apache.ibatis.executor.CachingExecutor.update(CachingExecutor.java:76)&#13;
	at org.apache.ibatis.session.defaults.DefaultSqlSession.update(DefaultSqlSession.java:194)&#13;
	at org.apache.ibatis.session.defaults.DefaultSqlSession.insert(DefaultSqlSession.java:181)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)&#13;
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)&#13;
	at java.lang.reflect.Method.invoke(Method.java:498)&#13;
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:427)&#13;
	... 39 more&#13;
Caused by: Error : 1400, Position : 607, Sql = INSERT INTO MEMBER (         
			    MEM_ID               
			   , MEM_PASS            
			   , MEM_NAME            
			   , MEM_REGNO1          
			   , MEM_REGNO2          
			   , MEM_BIR             
			   , MEM_ZIP             
			   , MEM_ADD1            
			   , MEM_ADD2            
			   , MEM_HOMETEL         
			   , MEM_COMTEL          
			   , MEM_HP              
			   , MEM_MAIL            
			   , MEM_JOB             
			   , MEM_LIKE            
			   , MEM_MEMORIAL        
			   , MEM_MEMORIALDAY    
			   , MEM_IMG 
			) VALUES (               
					:1 
					, :2 
					, :3 
					, :4 
					, :5 
					, :6 
					, :7 
					, :8 
					, :9 
					, :10 
					, :11 
					, :12 
					, :13 
					, :14 
					, :15 
					, :16 
					, :17 
					, :18 
			), OriginalSql = INSERT INTO MEMBER (         
			    MEM_ID               
			   , MEM_PASS            
			   , MEM_NAME            
			   , MEM_REGNO1          
			   , MEM_REGNO2          
			   , MEM_BIR             
			   , MEM_ZIP             
			   , MEM_ADD1            
			   , MEM_ADD2            
			   , MEM_HOMETEL         
			   , MEM_COMTEL          
			   , MEM_HP              
			   , MEM_MAIL            
			   , MEM_JOB             
			   , MEM_LIKE            
			   , MEM_MEMORIAL        
			   , MEM_MEMORIALDAY    
			   , MEM_IMG 
			) VALUES (               
					?
					, ?
					, ?
					, ?
					, ?
					, ?
					, ?
					, ?
					, ?
					, ?
					, ?
					, ?
					, ?
					, ?
					, ?
					, ?
					, ?
					, ?
			), Error Msg = ORA-01400: cannot insert NULL into ("DDIT"."MEMBER"."MEM_REGNO1")
&#13;
	at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:498)&#13;
	... 67 more&#13;
&#13;
</error>
    </testcase>
  </testsuite>
</testrun>
